[project]
name = "pyrros"
version = "0.1.0"
description = "Pyrros CLI tool"
authors = [
    { name = "Your Name", email = "your@email.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "rich",
    "questionary"
]

[project.scripts]
pyrros = "cli:main"
